version: '3.4'
services:
  realestateapi:
    image: realestateapi
    build:
      context: .
      dockerfile: RealEstate.API/Dockerfile
    ports:
      - 6001:80
    environment:
      - ConnectionStrings__Server=realestatedb;
      - ConnectionStrings__DB=RealEDb
      - ConnectionStrings__Username=sa
      - ConnectionStrings__Password=P@ssword123
    depends_on:
      - realestatedb
    restart: on-failure
  realestateweb:
    image: realestateweb
    build:
      context: .
      dockerfile: Real_Estate/Dockerfile
    ports:
      - 5001:80
    environment:
      - ConnectionStrings__Server=realestatedb;
      - ConnectionStrings__DB=RealEDb
      - ConnectionStrings__Username=sa
      - ConnectionStrings__Password=P@ssword123
    depends_on:
      - realestatedb
    restart: on-failure
  realestatedb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword123